[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.15.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"
