apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerpullsecrets
stringData:
  .dockerconfigjson: |
    {
      "auths" : {
        "my.harbor.deployment.org" : {
          {{ $authstring := (printf "%v:%v" .Values.secrets.harbor.username .Values.secrets.harbor.password ) }}
          "auth": "{{ $authstring | b64enc }}"
        }
      }
    }
